export default {
    products: [
        {
            _id: 123,
            name: 'Slim Dress Shirt',
            category: "Men's Tops",
            subCategory: 'Dress Shirts',
            image: '/images/d1.png',
            price: 60,
            brand: 'J. Crew',
            rating: 4.5,
            numReviews: 10,
            stock: 5,
        },
        {
            _id: 124,
            name: 'Tight jeans',
            category: "Women's Bottoms",
            subCategory: 'Jeans',
            image: '/images/tight-jeans.jpeg',
            price: 10,
            brand: 'Wrangler',
            rating: 1.3,
            numReviews: 5000,
            stock: 7,
        }, {
            _id: 125,
            name: 'Wool Blazer',
            category: "Men's Tops",
            subCategory: 'Coats',
            image: '/images/wool-blazer.jpeg',
            price: 150,
            brand: 'Ralph Lauren',
            rating: 4.9,
            numReviews: 20000,
            stock: 6,
        }, {
            _id: 126,
            name: 'Penny Loafers',
            category: "Men's Shoes",
            subCategory: "Dress Shoes",
            image: '/images/pennyloafers.jpeg',
            price: 85,
            brand: 'Dock Siders',
            rating: 2.5,
            numReviews: 2,
            stock: 10,
        }, {
            _id: 127,
            name: 'Adidas Original High Tops',
            category: "Men's Shoes",
            subCategory: "Athletic Shoes",
            image: '/images/adidas-originals-highs.jpeg',
            price: 30,
            brand: 'Adidas',
            rating: 3.2,
            numReviews: 150,
            stock: 3,
        }, {
            _id: 128,
            name: 'Kobe Bryant Jersey',
            category: "Women's Tops",
            subCategory: "Sports/Athletic",
            image: '/images/kobe-jersey.jpeg',
            price: 300,
            brand: 'Nike',
            rating: 6,
            numReviews: 999999,
            stock: 0,
        },
    ]
}